// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAjjKLAmGhnopKzEipOh7_TJKPZDsaa4o',
    appId: '1:451859692739:web:71bf463568188efca37676',
    messagingSenderId: '451859692739',
    projectId: 'chat-2a648',
    authDomain: 'chat-2a648.firebaseapp.com',
    storageBucket: 'chat-2a648.appspot.com',
    measurementId: 'G-VZXLKEHQ08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNMMK3fmtlyFIUR7zfDM7pIBj7Bdb9_V8',
    appId: '1:451859692739:android:4e49f85852d38c26a37676',
    messagingSenderId: '451859692739',
    projectId: 'chat-2a648',
    storageBucket: 'chat-2a648.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0tAlOY-Vbp63r5Lr0QYV1_xksfObk_0',
    appId: '1:451859692739:ios:b0ff6dd67a2d4be3a37676',
    messagingSenderId: '451859692739',
    projectId: 'chat-2a648',
    storageBucket: 'chat-2a648.appspot.com',
    iosClientId: '451859692739-caerbke6q1up6tudu6vnc8aqr290s6jj.apps.googleusercontent.com',
    iosBundleId: 'com.khaterCS.chat',
  );
}
